# redis:
#   image: redis
#   ports:
#     - "6379"
phpfpm:
  command: php-fpm --allow-to-run-as-root
  build: compose/images/php
  volumes:
    - /var/www/<%= projectName %>/compose/conf/fpm.conf:/usr/local/etc/php-fpm.conf
    - /var/www/<%= projectName %>:/var/www/html
    - /var/www/<%= projectName %>/compose/conf/php.ini:/usr/local/etc/php/conf.d/local.ini
  links:
    - mysql
    # - solr
    # - redis
    # - blackfire
mysql:
  command: mysqld --user=root --verbose
  image: mysql:5.6
  ports:
    - "3306"
  volumes:
    - /var/data/<%= projectName %>:/var/lib/mysql
    - /var/www/<%= projectName %>/compose/conf/mysql.cnf:/etc/mysql/my.cnf
  environment:
    MYSQL_DATABASE: data
    MYSQL_USER: mysql
    MYSQL_PASSWORD: mysql
    MYSQL_ALLOW_EMPTY_PASSWORD: yes
    MYSQL_ROOT_PASSWORD: root
nginx:
  image: nginx:1.9.0
  volumes:
    - /var/www/<%= projectName %>/compose/conf/nginx.conf:/etc/nginx/conf.d/default.conf
    - /var/www/<%= projectName %>:/var/www/html
  ports:
    - "80"
    - "443"
  links:
    - phpfpm
  environment:
    VIRTUAL_HOST: <%= projectName %>
# blackfire:
#   image: blackfire/blackfire
#   ports:
#     - "8707"
#   environment:
#     BLACKFIRE_SERVER_ID: <%= blackfireServerId %>
#     BLACKFIRE_SERVER_TOKEN: <%= blackfireServerToken %>
# solr:
#   image: solr:5.5
#   ports:
#     - "8983"
#   volumes:
#     - /var/www/<%= projectName %>/solr:/opt/solr/server/solr/<%= projectName %>
